import { USER } from "../util/constants";

// Test samples
export const users = [
  {
    _id: "22",
    fullName: "mike low",
    username: "miko",
    gender: "male",
    bio: null,
    conditions: [],
    disabled: false,
    password: "password",
    accountType: USER.ACCOUNT_TYPES.PROFESSIONAL,
    phone: null,
    email: "miko@mail.com",
    picture: null,
    experience: 3,
    speciality: ["stress management"],
    education: [
      {
        _id: "22",
        institution: "uoe",
        areaOfStudy: "math",
        startDate: new Date("2/2/2015"),
        endDate: new Date("2/2/2018"),
      },
    ],
    createdAt: new Date("2/3/1990"),
  },
  {
    _id: "23",
    fullName: "mitch mitch",
    username: "mitc",
    password: "password",
    gender: "female",
    bio: null,
    conditions: [],
    disabled: false,
    accountType: USER.ACCOUNT_TYPES.PROFESSIONAL,
    phone: null,
    email: "mitch@mail.com",
    picture: null,
    experience: 13,
    speciality: ["stress management"],
    education: [
      {
        _id: "22",
        institution: "uoe",
        areaOfStudy: "math",
        startDate: new Date("2/2/2015"),
        endDate: new Date("2/2/2018"),
      },
    ],
    createdAt: new Date("2/3/1995"),
  },
  {
    _id: "32",
    fullName: "st mary",
    username: "stmary",
    password: "password",
    gender: null,
    bio: null,
    conditions: [],
    disabled: false,
    accountType: USER.ACCOUNT_TYPES.INSTITUTION,
    phone: null,
    email: "stmary@mail.com",
    picture: null,
    experience: 13,
    speciality: ["stress management"],
    education: [
      {
        _id: "22",
        institution: "uoe",
        areaOfStudy: "math",
        startDate: new Date("2/2/2015"),
        endDate: new Date("2/2/2018"),
      },
    ],
    createdAt: new Date("2/3/2002"),
  },
  {
    _id: "24",
    fullName: "anto quan",
    username: "anto",
    password: "password",
    gender: "male",
    bio: null,
    conditions: ["anxiety"],
    disabled: false,
    accountType: USER.ACCOUNT_TYPES.PATIENT,
    phone: null,
    email: "anto@mail.com",
    picture: null,
    experience: 30,
    speciality: [],
    createdAt: new Date("2/3/2009"),
  },
  {
    _id: "41",
    fullName: "rallo kins",
    username: "rallo",
    password: "password",
    gender: "male",
    bio: null,
    conditions: ["anxiety"],
    disabled: false,
    accountType: null,
    phone: null,
    email: "rallo@mail.com",
    picture: null,
    experience: 30,
    speciality: [],
    createdAt: new Date("2/3/1990"),
  },
];

export const conditions = [
  {
    _id: "1",
    name: "depression",
    body: "some long text on depression",
    symptomps: "symps\nsymps\nmore symps",
    remedies: "shoes\nshoes\nmore shoes",
    createdAt: new Date("2/9/2019"),
    disabled: false,
  },
  {
    _id: "2",
    name: "anxiety",
    body: "some long text on anxeity",
    symptomps: "symps\nsymps\nmore symps",
    remedies: "shoes\nshoes\nmore shoes",
    createdAt: new Date("2/9/2015"),
    disabled: false,
  },
  {
    _id: "3",
    name: "trauma",
    body: "some long text on trauma",
    symptomps: "symps\nsymps\nmore symps",
    remedies: "shoes\nshoes\nmore shoes",
    createdAt: new Date("2/9/2020"),
    disabled: false,
  },
];
